# permissions for end users to edit overseerruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseerrun-editor-role
rules:
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseerruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseerruns/status
  verbs:
  - get
