# permissions for end users to edit overseers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseer-editor-role
rules:
- apiGroups:
  - overseer.quanxiang.cloud.io
  resources:
  - overseers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - overseer.quanxiang.cloud.io
  resources:
  - overseers/status
  verbs:
  - get
