# permissions for end users to view overseerruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseerrun-viewer-role
rules:
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseerruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseerruns/status
  verbs:
  - get
