apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: overseer-sample
spec:
  params:
    - name: foo
      default: ""
  steps:
    - name: overseer-sample
      image: ubuntu
      command:
        - echo
      args:
        - "$(params.foo)"
---
apiVersion: quanxiang.cloud.io/v1alpha1
kind: Overseer
metadata:
  name: overseer-sample
spec:
  description: |
    this is overseer sample.
  params:
    - name: FOO
      description: the param`s name
      default: bar
  steps:
    - name: tekton-task-echo
      template: |
          apiVersion: tekton.dev/v1beta1
          kind: TaskRun
          metadata:
             name: overseer-sample
          taskRef:
            - name: overseer-sample
              params:
                - name: foo
                  value: $(params.FOO)